    steps:
      - uses: actions/checkout@v5
      
      - name: Set up OpenJDK 17
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "17"
          cache: 'gradle' # تفعيل الكاش المدمج أسرع وأفضل

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install required platform
        run: sdkmanager "platforms;android-35" "build-tools;35.0.0"

      # قمنا بحذف سطر "Replace android.jar" لأننا نستخدم مكتبة HiddenApiBypass 
      # وهي تغنيك عن استبدال ملف النظام وتجعل البناء أكثر استقراراً

      - name: Build APK
        id: build_apk
        run: |
          chmod +x gradlew
          if [[ "${BUILD_TYPE}" = "release" ]]; then
            ./gradlew assembleRelease
            echo "upload_filename=${RUN_ID}-Release-APK" >> $GITHUB_OUTPUT
            echo "build_filename=app-release-unsigned.apk" >> $GITHUB_OUTPUT
          else
            ./gradlew assembleDebug
            echo "upload_filename=${RUN_ID}-Debug-APK" >> $GITHUB_OUTPUT
            echo "build_filename=app-debug.apk" >> $GITHUB_OUTPUT
          fi
        env:
          BUILD_TYPE: ${{ inputs.build-type }}
          RUN_ID: ${{ github.run_id }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build_apk.outputs.upload_filename }}
          path: app/build/outputs/apk/**/*.apk # سيبحث عن الـ APK المرفوع أياً كان مساره
          retention-days: 3
